export const FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE.REQUEST';
export const FETCH_PEOPLE_DONE = 'FETCH_PEOPLE.DONE';
export const FETCH_PEOPLE_ERROR = 'FETCH_PEOPLE.ERROR';
export const MOVE_ID = 'MOVE_ID';
export const CHANGE_FILTER = 'CHANGE_FILTER';
